---
- name: Create configuration
  ansible.builtin.template:
    src: "{{ vector_template }}"
    dest: "{{ vector_config_file }}"
    mode: "0644"
  notify: Restart vector

- name: Add vector to specified groups
  when:
    - vector_groups is defined
    - vector_groups | length > 0
  ansible.builtin.user:
    name: vector
    groups: "{{ item }}"
    append: true
  loop: "{{ vector_groups }}"
  notify: Restart vector

- name: Start vector
  ansible.builtin.service:
    state: restarted
    enabled: true
    name: vector
