---

- name: Create repository for debian or redhat based systems
  when: vector_install_from_repo | bool
  ansible.builtin.include_tasks: repo.yml

- name: Install vector
  ansible.builtin.include_tasks: install.yml

- name: Create configuration for vector
  ansible.builtin.include_tasks: config.yml
