---

- name: Configure repository and Repository key on Debian
  when: ansible_os_family == "Debian"
  block:
    - name: Ensure apt-transport-https curl and gnupg are installed
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - curl
          - gnupg
        state: present
        update_cache: true

    - name: Create key file /usr/share/keyrings/datadog-archive-keyring.gpg
      ansible.builtin.file:
        path: /usr/share/keyrings/datadog-archive-keyring.gpg
        mode: "0644"
        owner: root
        group: root
        state: touch

    - name: Download key and put them into key file
      ansible.builtin.shell: |
        set -o pipefail
        curl {{ item }} | gpg --no-default-keyring --keyring /usr/share/keyrings/datadog-archive-keyring.gpg --import --batch
      register: download_repo_key
      changed_when: true
      failed_when: download_repo_key.rc != 0
      args:
        executable: /bin/bash
      loop: "{{ vector_repo_key[ansible_os_family] }}"

    - name: Add vector repository
      ansible.builtin.apt_repository:
        repo: "{{ vector_repo[ansible_os_family] }}"
        state: present
        filename: vector

- name: Add vector repository for RedHat based distributions
  when: ansible_os_family == "RedHat"
  ansible.builtin.yum_repository:
    name: vector
    description: Vector
    baseurl: "{{ vector_repo[ansible_os_family] }}"
    gpgcheck: true
    repo_gpgcheck: "{{ vector_repo_gpgcheck }}"
    gpgkey: "{{ vector_repo_key[ansible_os_family] }}"
